name: Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src/clj graal/clj src/cljs dev/clj
          github_token: ${{ secrets.GITHUB_TOKEN }}
  warn-on-reflect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Check for clj files that do not warn on reflect
        shell: bash
        run: |
          if [ -z "$(grep -rL '*warn-on-reflection*' src/clj)" ]
          then
            exit 0
          else
            exit 1
          fi
