name: Build GitHub Pages Cryogen
on:
  push:
    branches: [ master ]
    paths:
      - 'cryogen'
  workflow_dispatch:
jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-java@v3.1.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v3.0.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('cryogen/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: clojure -M:build
        working-directory: ./cryogen
      - uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cryogen/public/skylobby
