name: Build Release Artifacts

on:
  release:
    types: [created]

jobs:
  build-deb:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2.3.1
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: clojure -M:cljs compile frontend
      - run: clojure -M:uberjar:headless
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/${{ env.CI_REPOSITORY_NAME }}.jar
          asset_name: ${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}-linux.jar
          asset_content_type: application/java-archive
      # linux jar without version
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/${{ env.CI_REPOSITORY_NAME }}.jar
          asset_name: ${{ env.CI_REPOSITORY_NAME }}-linux.jar
          asset_content_type: application/java-archive
      - run: jpackage --app-version ${{ env.CI_REF_NAME }} @jpackage/lobby @jpackage/linux
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.CI_REPOSITORY_NAME }}_${{ env.CI_REF_NAME }}-1_amd64.deb
          asset_name: ${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}_linux-amd64.deb
          asset_content_type: application/vnd.debian.binary-package
  build-dmg:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2.3.1
      - uses: actions/setup-java@v2
        with:
          java-version: '14'
          # ^ mac jpackage hates versions starting with 0 in later versions
          distribution: 'adopt'
      - uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: clojure -M:cljs compile frontend
      - run: clojure -M:uberjar:headless
      # mac jar without version
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/${{ env.CI_REPOSITORY_NAME }}.jar
          asset_name: ${{ env.CI_REPOSITORY_NAME }}-mac.jar
          asset_content_type: application/java-archive
      - run: jpackage --app-version ${{ env.CI_REF_NAME }} @jpackage/lobby @jpackage/mac
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}.dmg
          asset_name: ${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}_mac.dmg
          asset_content_type: application/x-apple-diskimage
  build-exe:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2.3.1
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: clojure -M:cljs compile frontend
        shell: powershell
      - run: clojure -M:uberjar:headless
        shell: powershell
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/${{ env.CI_REPOSITORY_NAME }}.jar
          asset_name: ${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}-windows.jar
          asset_content_type: application/java-archive
      - run: cp package/win/* target
      - run: jpackage --app-version ${{ env.CI_REF_NAME }} @jpackage/lobby @jpackage/windows
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}.msi
          asset_name: ${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}_windows.msi
          asset_content_type: application/x-msi
      # windows installer without version in filename
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}.msi
          asset_name: ${{ env.CI_REPOSITORY_NAME }}-windows.msi
          asset_content_type: application/x-msi
  mark-latest-release:
    needs: [build-deb, build-exe, build-dmg]
    runs-on: ubuntu-20.04
    steps:
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
      - uses: FranzDiebold/github-env-vars-action@v2.3.1
      - uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "https://github.com/skynet-gh/skylobby/releases/tag/${{ env.CI_REF_NAME }}"
