name: Unit test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: ['11', '17']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-java@v3.4.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - uses: DeLaGuardo/setup-clojure@7.0
        with:
          cli: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v3.0.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - if: ${{ matrix.os != 'windows-latest' }}
        run: clojure -M:test:headless:runner
        shell: bash
      - if: ${{ matrix.os == 'windows-latest' }}
        run: clojure -M:test:headless:runner
        shell: powershell
  coverage:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-java@v3.4.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: DeLaGuardo/setup-clojure@7.0
        with:
          cli: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: clojure -M:coverage:headless
      - run: bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
